### ISSUE TITLE
smart contract to add mechanism to force or attract memebt to contribute on time 

### ISSUE THREAD

**Issue by Sufiyan-dev** [Owujupe/ComFi#3]
I am working on buiulding the logic of the contract, were we can add feature like penalities or adding grace period. 

Or maybe we can not have the time restriction in which until all the participated to the payment then only we proceed further with distribution then there will be an fix amount of down time or pause period in our situation is 2 weeks then again we will wait for other participates to contribute and proceed further. 

@jonasgodfrey

**Comment by Sufiyan-dev** [comment]
coming up wiht V0 (we take every participant is trustworthy)

so we give each members in the group 2 week time to make the contribution after the start time. as soon as all the participate make the payment there will be winner announced but the winner can only claim the amount after the deadline of the contribution. 

so we assume that everyone one will make payment in the specified time.

@jonasgodfrey

**Comment by jonasgodfrey** [comment]
As discussed we can approach it this way for version 1.
However, each participant is expected to know when they will be receiving their own

**Comment by jonasgodfrey** [comment]
Here is the flow: Just like the fiat option
Step 1: Create Group (state group name, amount, frequency and start date)
Step 2: Onboard members via Group Id and Join Code
Step 3: Assign Positions: Randomly
Step 4: Members donate within periods selected
Step 5: Payout the first member

**Comment by Sufiyan-dev** [comment]
Fixed the wiht V0
